<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Empleado;
use Illuminate\Support\Str;

class EmpleadoSeeder extends Seeder
{
    public function run(): void
    {
        $empleados = [
            [
                'codigo_empleado' => 'EMP001',
                'nombres' => 'Juan Carlos',
                'apellidos' => 'García Rodríguez',
                'email' => 'juan.garcia@empresa.com',
                'telefono' => '987654321',
                'dni' => '12345678',
                'fecha_nacimiento' => '1985-03-15',
                'genero' => 'masculino',
                'estado_civil' => 'casado',
                'direccion' => 'Av. Los Álamos 123, San Isidro',
                'distrito' => 'San Isidro',
                'provincia' => 'Lima',
                'departamento' => 'Lima',
                'contacto_emergencia_nombre' => 'María García',
                'contacto_emergencia_telefono' => '987654322',
                'contacto_emergencia_relacion' => 'Esposa',
                'numero_hijos' => 2,
                'conyuge_nombre' => 'María García López',
                'conyuge_dni' => '87654321',
                'nivel_educacion' => 'universitario',
                'centro_estudios' => 'Universidad Nacional Mayor de San Marcos',
                'carrera_profesion' => 'Administración de Empresas',
                'departamento_trabajo' => 'Administración',
                'cargo' => 'Gerente de Operaciones',
                'sueldo_base' => 4500.00,
                'fecha_ingreso' => '2020-01-15',
                'tipo_contrato' => 'indefinido',
                'regimen_pensionario' => 'SPP',
                'afp_proveedor' => 'PRIMA',
                'cuspp' => '123456789012',
                'asignacion_familiar' => true,
                'banco' => 'BCP',
                'numero_cuenta' => '19100123456789',
                'cci' => '00219100123456789012',
                'grupo_sanguineo' => 'O+'
            ],
            [
                'codigo_empleado' => 'EMP002',
                'nombres' => 'Ana María',
                'apellidos' => 'Flores Vásquez',
                'email' => 'ana.flores@empresa.com',
                'telefono' => '987654323',
                'dni' => '23456789',
                'fecha_nacimiento' => '1990-07-22',
                'genero' => 'femenino',
                'estado_civil' => 'soltero',
                'direccion' => 'Jr. Las Flores 456, Miraflores',
                'distrito' => 'Miraflores',
                'provincia' => 'Lima',
                'departamento' => 'Lima',
                'contacto_emergencia_nombre' => 'Roberto Flores',
                'contacto_emergencia_telefono' => '987654324',
                'contacto_emergencia_relacion' => 'Padre',
                'numero_hijos' => 0,
                'nivel_educacion' => 'universitario',
                'centro_estudios' => 'Universidad de Lima',
                'carrera_profesion' => 'Contabilidad',
                'departamento_trabajo' => 'Contabilidad',
                'cargo' => 'Contador Senior',
                'sueldo_base' => 3200.00,
                'fecha_ingreso' => '2021-03-01',
                'tipo_contrato' => 'indefinido',
                'regimen_pensionario' => 'SPP',
                'afp_proveedor' => 'INTEGRA',
                'cuspp' => '234567890123',
                'asignacion_familiar' => false,
                'banco' => 'BBVA',
                'numero_cuenta' => '00111234567890',
                'cci' => '01111234567890123456',
                'grupo_sanguineo' => 'A+'
            ],
            [
                'codigo_empleado' => 'EMP003',
                'nombres' => 'Luis Alberto',
                'apellidos' => 'Mendoza Castillo',
                'email' => 'luis.mendoza@empresa.com',
                'telefono' => '987654325',
                'dni' => '34567890',
                'fecha_nacimiento' => '1988-11-08',
                'genero' => 'masculino',
                'estado_civil' => 'conviviente',
                'direccion' => 'Av. Universitaria 789, Los Olivos',
                'distrito' => 'Los Olivos',
                'provincia' => 'Lima',
                'departamento' => 'Lima',
                'contacto_emergencia_nombre' => 'Carmen Castillo',
                'contacto_emergencia_telefono' => '987654326',
                'contacto_emergencia_relacion' => 'Conviviente',
                'numero_hijos' => 1,
                'conyuge_nombre' => 'Carmen Castillo Torres',
                'conyuge_dni' => '45678901',
                'nivel_educacion' => 'tecnico',
                'centro_estudios' => 'TECSUP',
                'carrera_profesion' => 'Técnico en Sistemas',
                'departamento_trabajo' => 'Tecnología',
                'cargo' => 'Analista de Sistemas',
                'sueldo_base' => 2800.00,
                'fecha_ingreso' => '2019-06-15',
                'tipo_contrato' => 'indefinido',
                'regimen_pensionario' => 'SNP',
                'asignacion_familiar' => true,
                'banco' => 'INTERBANK',
                'numero_cuenta' => '8981234567890',
                'cci' => '00389812345678901234',
                'grupo_sanguineo' => 'B+'
            ],
            [
                'codigo_empleado' => 'EMP004',
                'nombres' => 'Carmen Rosa',
                'apellidos' => 'Torres Huamán',
                'email' => 'carmen.torres@empresa.com',
                'telefono' => '987654327',
                'dni' => '45678901',
                'fecha_nacimiento' => '1992-04-30',
                'genero' => 'femenino',
                'estado_civil' => 'soltero',
                'direccion' => 'Av. Túpac Amaru 321, Rímac',
                'distrito' => 'Rímac',
                'provincia' => 'Lima',
                'departamento' => 'Lima',
                'contacto_emergencia_nombre' => 'Rosa Huamán',
                'contacto_emergencia_telefono' => '987654328',
                'contacto_emergencia_relacion' => 'Madre',
                'numero_hijos' => 0,
                'nivel_educacion' => 'universitario',
                'centro_estudios' => 'Universidad César Vallejo',
                'carrera_profesion' => 'Psicología',
                'departamento_trabajo' => 'Recursos Humanos',
                'cargo' => 'Especialista en RRHH',
                'sueldo_base' => 2500.00,
                'fecha_ingreso' => '2022-08-01',
                'tipo_contrato' => 'temporal',
                'regimen_pensionario' => 'SPP',
                'afp_proveedor' => 'PROFUTURO',
                'cuspp' => '345678901234',
                'asignacion_familiar' => false,
                'banco' => 'SCOTIABANK',
                'numero_cuenta' => '3911234567890',
                'cci' => '00939112345678901234',
                'grupo_sanguineo' => 'AB+'
            ],
            [
                'codigo_empleado' => 'EMP005',
                'nombres' => 'Miguel Ángel',
                'apellidos' => 'Quispe Mamani',
                'email' => 'miguel.quispe@empresa.com',
                'telefono' => '987654329',
                'dni' => '56789012',
                'fecha_nacimiento' => '1987-09-12',
                'genero' => 'masculino',
                'estado_civil' => 'casado',
                'direccion' => 'Jr. Ayacucho 654, Breña',
                'distrito' => 'Breña',
                'provincia' => 'Lima',
                'departamento' => 'Lima',
                'contacto_emergencia_nombre' => 'Elena Mamani',
                'contacto_emergencia_telefono' => '987654330',
                'contacto_emergencia_relacion' => 'Esposa',
                'numero_hijos' => 3,
                'conyuge_nombre' => 'Elena Mamani Cruz',
                'conyuge_dni' => '67890123',
                'nivel_educacion' => 'secundaria',
                'centro_estudios' => 'Colegio Nacional Túpac Amaru',
                'departamento_trabajo' => 'Operaciones',
                'cargo' => 'Operario',
                'sueldo_base' => 1200.00,
                'fecha_ingreso' => '2018-02-20',
                'tipo_contrato' => 'indefinido',
                'regimen_pensionario' => 'SNP',
                'asignacion_familiar' => true,
                'banco' => 'BANCO_NACION',
                'numero_cuenta' => '0001234567890',
                'cci' => '01800012345678901234',
                'grupo_sanguineo' => 'O-'
            ]
        ];

        foreach ($empleados as $datosEmpleado) {
            Empleado::updateOrCreate(
                ['dni' => $datosEmpleado['dni']],
                $datosEmpleado
            );
        }
    }
}